on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create QA-reports build and test jobs
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: "ls -la"
      - name: Store lava job
        uses: actions/upload-artifact@v4
        with:
          name: lava-job
          path: lava.yaml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: lava-job
      - name: submit
        uses: mwasilew/qa-reports-action@HEAD
        with:
          qa_reports_token: ${{ secrets.TOKEN }}
          qa_reports_url: "qa-reports.foundries.io"
          qa_reports_group: "qcom"
          qa_reports_project: "test-workflow" 
          qa_reports_environment: "${{ inputs.machine }}"
          qa_reports_build: "${{ github.sha }}"
          qa_reports_patch_source: "mwasilew-test"
          qa_reports_lava_backend: "lava.infra.foundries.io"
          job_definition: "lava.yaml"

