on: [workflow_dispatch, pull_request, push]

jobs:
  submit_lava_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    name: Create QA-reports build and test jobs
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: "ls -la"
      - name: submit
        uses: mwasilew/qa-reports-action@HEAD
        with:
          qa_reports_token: ${{ secrets.TOKEN }}
          qa_reports_url: "qa-reports.foundries.io"
          qa_reports_group: "qcom"
          qa_reports_project: "test-workflow" 
          qa_reports_environment: "${{ matrix.machine }}"
          qa_reports_build: "${{ github.sha }}"
          qa_reports_patch_source: "mwasilew-test"
          qa_reports_lava_backend: "lava.infra.foundries.io"
          job_definition: "lava.yaml"

