name: Matrix Workflow

on: [workflow_dispatch, pull_request, push]

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    uses: ./.github/workflows/build-and-test.yml # calls the one above ^
    with:
      version: ${{ matrix.machine }}
    secrets: inherit

